// "use client";
import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_component/Navbar/Navbar";
import Footer from "./_component/Footer/Footer";
import NextAuthProvider from "./Providers/nextAuthProvider";
import Providers from "./Providers/react-query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NextAuthProvider>
            <Toaster />
            <Navbar />
            <div className="container mx-auto max-w-7xl">{children}</div>
            <Footer />
          </NextAuthProvider>
        </Providers>
      </body>
    </html>

    // <html lang="en" suppressHydrationWarning>
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased `}
    //   >
    //     <Navbar />
    //     <div className="container mx-auto max-w-7xl">{children}</div>
    //     <Footer />
    //   </body>
    // </html>
  );
}
